# res://scripts/Localization.gd
class_name Localization
extends Node

const DATA = {
	"ru": {
		"ERR_NATURAL_NO_DRAW": "Ошибка! При натурале нельзя брать третьи карты.",
		"ERR_PLAYER_MUST_DRAW": "Ошибка! Игроку с %d очками нужна третья карта.",
		"ERR_PLAYER_NO_DRAW": "Ошибка! Игроку с %d очками не нужна третья карта.",
		"ERR_BANKER_MUST_DRAW": "Ошибка! Банкиру с %d очками нужна третья карта.",
		"ERR_BANKER_NO_DRAW": "Ошибка! Банкиру с %d очками не нужна третья карта.",
		"ERR_BANKER_MUST_DRAW_AFTER_PLAYER": "Ошибка! Банкиру нужна третья карта после карты Игрока %s.",
		"ERR_ALL_CARDS_OPENED": "Ошибка! Все карты уже открыты. Нажмите на маркер победителя.",
		"ERR_OPEN_FIRST_CARDS": "Сначала откройте первые 4 карты.",
		"ERR_FINISH_THIRD_CARDS": "Сначала завершите раздачу третьих карт или закажите их при необходимости.",
		"ERR_OPEN_BANKER_CARD": "Сначала откройте карту Банкира (ему нужна третья карта).",
		"ERR_FINISH_DEAL": "Сначала завершите раздачу.",
		"INFO_NATURAL_CHOOSE_WINNER": "Натурал! Выберите победителя без нажатия 'Карты'.",
		"INFO_BANKER_DEPENDS_ON_PLAYER": "Решение для Банкира зависит от третьей карты Игрока. Сначала откройте её.",
		"INFO_PLAYER_CARD_OPENED": "Карта Игрока открыта: %s. Теперь решите про Банкира.",
		"INFO_BANKER_NO_DRAW_CHOOSE_WINNER": "Банкиру не нужна третья карта. Переходим к выбору победителя.",
		"INFO_ALL_OPENED_CHOOSE_WINNER": "Все карты открыты. Выберите победителя.",
		"INFO_PLAYER_THIRD": "Player третья карта: %s",
		"INFO_BANKER_THIRD": "Banker третья карта: %s",
		"WIN_CORRECT": "Верно! Выиграл %s: %s",
		"WIN_INCORRECT": "Ошибка! Выбрано: %s, но выиграл %s: %s",
		"WIN_PLAYER": "Игрок",
		"WIN_BANKER": "Банкир",
		"WIN_TIE": "Ничья",
		"PAIR_PLAYER_TITLE": "Пара Игрока 11:1",
		"PAIR_BANKER_TITLE": "Пара Банкира 11:1",
		"ACTION_BUTTON_CARDS": "Карты",
		"HELP_TITLE": "Таблица третьих карт Банкира",
		"HELP_BANKER": "Банкир",
		"HELP_PLAYER_THIRD": "Третья карта Игрока",
		"HELP_DRAW": "Берёт",
		"HELP_NO_DRAW": "Не берёт",
		"BET_AMOUNT": "Ставка: %d",
		"BANKER_BET": "Ставка на Банкира: %d",
		"TIE_BET": "Ставка на Ничью: %d",
		"COMMISSION_CORRECT": "Верно! Выплата (комиссия): %d",
		"COMMISSION_INCORRECT": "Ошибка! Правильная выплата: %d",
		"TIE_PAYOUT_CORRECT": "Верно! Выплата Ничья (8:1): %d",
		"TIE_PAYOUT_INCORRECT": "Ошибка! Правильная выплата Ничья: %d",
		"ERR_INVALID_INPUT": "Неверный ввод! Введите целое число.",
		"BOTH_CARDS_NEEDED": "Нужны ОБЕ третьи карты.",
		"BANKER_NO_CARD_YET": "Банкиру НЕ нужна третья карта пока.",
		"BOTH_WRONG": "Ошибка! Отметьте ОБЕ третьи карты.",
		"PAYOUT_BUTTON": "Выплатить",
		"PAYOUT_STAKE": "Ставка: %s",
		"PAYOUT_AMOUNT_EMPTY": "Выплата: —",
		"PAYOUT_AMOUNT": "Выплата: %d",
		"DAMIKU": "Дамику",
		"VICTORY_BANKER": "Выигрывает Банкир: %d vs %d",
		"VICTORY_PLAYER": "Выигрывает Игрок: %d vs %d",
		"VICTORY_TIE": "Игалите",
		"PAYOUT_TOGGLE_PLAYER": "Выплата игрок",
		"PAYOUT_TOGGLE_BANKER": "Выплата банкир",
		"PAYOUT_TOGGLE_TIE": "Выплата ничья",
		"BET_PROFILE": "Профиль ставок",
		"BET_PROFILE_SMALL": "Малые",
		"BET_PROFILE_MEDIUM": "Средние",
		"BET_PROFILE_LARGE": "Крупные",
		"BET_PROFILE_DESC_SMALL": "Мелкие ставки для тренировки",
		"BET_PROFILE_DESC_MEDIUM": "Реалистичная игра",
		"BET_PROFILE_DESC_LARGE": "Имитация богатого клиента",
		"ERR_UNPAID_BETS": "Ошибка! Осталось %d неоплаченных выплат. Оплатите их, нажав на фишки.",
		"ALL_PAYOUTS_COMPLETED": "Все выплаты оплачены! Можно начинать новую игру.",
		"ERR_WRONG_WINNER": "Ошибка! Неправильный выбор. Выиграл %s",
		"VICTORY_TOAST": "Выигрывает %s: %d vs %d",
		"PAYOUT_EMPTY_WARNING": "Ничего не забыл?"
	},
	"en": {
		"ERR_NATURAL_NO_DRAW": "Error! Natural — no third cards allowed.",
		"ERR_PLAYER_MUST_DRAW": "Error! Player with %d points must draw.",
		"ERR_PLAYER_NO_DRAW": "Error! Player with %d points must stand.",
		"ERR_BANKER_MUST_DRAW": "Error! Banker with %d points must draw.",
		"ERR_BANKER_NO_DRAW": "Error! Banker with %d points must stand.",
		"ERR_BANKER_MUST_DRAW_AFTER_PLAYER": "Error! Banker must draw after Player's %s.",
		"ERR_ALL_CARDS_OPENED": "Error! All cards are open. Choose winner.",
		"ERR_OPEN_FIRST_CARDS": "First deal 4 cards.",
		"ERR_FINISH_THIRD_CARDS": "Finish third card decisions first.",
		"ERR_OPEN_BANKER_CARD": "First open Banker's third card.",
		"ERR_FINISH_DEAL": "Complete the deal first.",
		"INFO_NATURAL_CHOOSE_WINNER": "Natural! Choose winner without 'Cards'.",
		"INFO_BANKER_DEPENDS_ON_PLAYER": "Banker depends on Player's third card. Open it first.",
		"INFO_PLAYER_CARD_OPENED": "Player's card: %s. Now decide for Banker.",
		"INFO_BANKER_NO_DRAW_CHOOSE_WINNER": "Banker stands. Choose winner.",
		"INFO_ALL_OPENED_CHOOSE_WINNER": "All cards open. Choose winner.",
		"INFO_PLAYER_THIRD": "Player third: %s",
		"INFO_BANKER_THIRD": "Banker third: %s",
		"WIN_CORRECT": "Correct! Winner: %s — %s",
		"WIN_INCORRECT": "Wrong! You chose %s, but winner is %s — %s",
		"WIN_PLAYER": "Player",
		"WIN_BANKER": "Banker",
		"WIN_TIE": "Tie",
		"PAIR_PLAYER_TITLE": "Player Pair 11:1",
		"PAIR_BANKER_TITLE": "Banker Pair 11:1",
		"ACTION_BUTTON_CARDS": "Cards",
		"HELP_TITLE": "Banker Third Card Table",
		"HELP_BANKER": "Banker",
		"HELP_PLAYER_THIRD": "Player's Third",
		"HELP_DRAW": "Draw",
		"HELP_NO_DRAW": "Stand",
		"BET_AMOUNT": "Bet: %d",
		"BANKER_BET": "Banker Bet: %d",
		"TIE_BET": "Tie Bet: %d",
		"COMMISSION_CORRECT": "Correct! Payout (commission): %d",
		"COMMISSION_INCORRECT": "Wrong! Correct payout: %d",
		"TIE_PAYOUT_CORRECT": "Correct! Tie payout (8:1): %d",
		"TIE_PAYOUT_INCORRECT": "Wrong! Correct Tie payout: %d",
		"ERR_INVALID_INPUT": "Invalid input! Enter an integer.",
		"BOTH_CARDS_NEEDED": "Both third cards needed.",
		"BANKER_NO_CARD_YET": "Banker doesn't need third card yet.",
		"BOTH_WRONG": "Error! Mark BOTH third cards.",
		"PAYOUT_BUTTON": "Payout",
		"PAYOUT_STAKE": "Stake: %s",
		"PAYOUT_AMOUNT_EMPTY": "Payout: —",
		"PAYOUT_AMOUNT": "Payout: %d",
		"DAMIKU": "No bets",
		"VICTORY_BANKER": "Banker Wins: %d vs %d",
		"VICTORY_PLAYER": "Player Wins: %d vs %d",
		"VICTORY_TIE": "Tie",
		"PAYOUT_TOGGLE_PLAYER": "Player payout",
		"PAYOUT_TOGGLE_BANKER": "Banker payout",
		"PAYOUT_TOGGLE_TIE": "Tie payout",
		"BET_PROFILE": "Bet profile",
		"BET_PROFILE_SMALL": "Small",
		"BET_PROFILE_MEDIUM": "Medium",
		"BET_PROFILE_LARGE": "Large",
		"BET_PROFILE_DESC_SMALL": "Small bets for practice",
		"BET_PROFILE_DESC_MEDIUM": "Realistic gameplay",
		"BET_PROFILE_DESC_LARGE": "High roller simulation",
		"ERR_UNPAID_BETS": "Error! %d unpaid payouts remaining. Click on chips to pay them.",
		"ALL_PAYOUTS_COMPLETED": "All payouts completed! You can start a new game.",
		"ERR_WRONG_WINNER": "Error! Wrong choice. Winner is %s",
		"VICTORY_TOAST": "%s Wins: %d vs %d",
		"PAYOUT_EMPTY_WARNING": "Didn't forget anything?"
	}
}

static var _current_lang: String = "ru"

static func t(key: String, args = []) -> String:
	var text = DATA[_current_lang].get(key, key)
	if args.size() > 0:
		text = text % args
	return text

static func set_lang(lang: String):
	if lang in DATA:
		_current_lang = lang
		
static func get_lang() -> String:
	return _current_lang
