# res://scripts/Localization.gd
class_name Localization
extends Node

const DATA = {
	"ru": {
		"ERR_NATURAL_NO_DRAW": "Натуральная 8 или 9! Третья карта не берётся",
		"ERR_PLAYER_MUST_DRAW": "Ошибка! Игроку с %d очками нужна третья карта.",
		"ERR_PLAYER_NO_DRAW": "Ошибка! Игроку с %d очками не нужна третья карта.",
		"ERR_BANKER_MUST_DRAW": "Ошибка! Банкиру с %d очками нужна третья карта.",
		"ERR_BANKER_NO_DRAW": "Ошибка! Банкиру с %d очками не нужна третья карта.",
		"ERR_BANKER_MUST_DRAW_AFTER_PLAYER": "Ошибка! Банкиру нужна третья карта после карты Игрока %s.",
		"ERR_ALL_CARDS_OPENED": "Ошибка! Все карты уже открыты. Нажмите на маркер победителя.",
		"ERR_OPEN_FIRST_CARDS": "Сначала откройте первые 4 карты.",
		"ERR_FINISH_THIRD_CARDS": "Сначала завершите раздачу третьих карт или закажите их при необходимости.",
		"ERR_OPEN_BANKER_CARD": "Сначала откройте карту Банкира (ему нужна третья карта).",
		"ERR_FINISH_DEAL": "Сначала завершите раздачу.",
		"ERR_TIE_WRONG": "Ошибка!",
		"INFO_NATURAL_CHOOSE_WINNER": "Натуральная 8 или 9! Выбирайте победителя",
		"INFO_BANKER_DEPENDS_ON_PLAYER": "Решение для Банкира зависит от третьей карты Игрока. Сначала откройте её.",
		"INFO_PLAYER_CARD_OPENED": "Карта Игрока открыта: %s. Теперь решите про Банкира.",
		"INFO_BANKER_NO_DRAW_CHOOSE_WINNER": "Банкиру не нужна третья карта. Переходим к выбору победителя.",
		"INFO_ALL_OPENED_CHOOSE_WINNER": "Все карты открыты. Выберите победителя.",
		"INFO_PLAYER_THIRD": "Player третья карта: %s",
		"INFO_BANKER_THIRD": "Banker третья карта: %s",
		"WIN_CORRECT": "Верно! Выиграл %s: %s",
		"WIN_INCORRECT": "Ошибка! Выбрано: %s, но выиграл %s: %s",
		"WIN_PLAYER": "Игрок",
		"WIN_BANKER": "Банкир",
		"WIN_TIE": "Игалите",
		"PLAYER": "Игрок",
		"BANKER": "Банкир",
		"TIE_BUTTON": "Игалите",
		"PAIR_PLAYER_TITLE": "Пара Игрока",
		"PAIR_BANKER_TITLE": "Пара Банкира",
		"ACTION_BUTTON_CARDS": "Карты",
		"TOPBAR_HELP": "Шпаргалка",
		"TOPBAR_SETTINGS": "Настройки",
		"TOPBAR_ROUNDS": "Раздача: %d",
		"TOPBAR_TIPS": "Чаевые: %d",
		"HELP_TITLE": "Таблица третьих карт Банкира",
		"HELP_BANKER": "Банкир",
		"HELP_PLAYER_THIRD": "Третья карта Игрока",
		"HELP_DRAW": "Берёт",
		"HELP_NO_DRAW": "Не берёт",
		"BET_AMOUNT": "Ставка: %d",
		"BANKER_BET": "Ставка на Банкира: %d",
		"TIE_BET": "Ставка на Ничью: %d",
		"COMMISSION_CORRECT": "Верно! Выплата (комиссия): %d",
		"COMMISSION_INCORRECT": "Ошибка! Правильная выплата: %d",
		"TIE_PAYOUT_CORRECT": "Верно! Выплата Ничья (8:1): %d",
		"TIE_PAYOUT_INCORRECT": "Ошибка! Правильная выплата Ничья: %d",
		"ERR_INVALID_INPUT": "Неверный ввод! Введите целое число.",
		"BOTH_CARDS_NEEDED": "Нужны ОБЕ третьи карты.",
		"BANKER_NO_CARD_YET": "Банкиру НЕ нужна третья карта пока.",
		"BOTH_WRONG": "Ошибка! Отметьте ОБЕ третьи карты.",
		"PAYOUT_BUTTON": "Выплатить",
		"PAYOUT_STAKE": "Ставка: %s",
		"PAYOUT_AMOUNT_EMPTY": "Выплата: —",
		"PAYOUT_AMOUNT": "Выплата: %d",
		"DAMIKU": "Дамику",
		"DAMIKU_NO_BETS": "Дамику! (раздача без ставок)",
		"DAMIKU_ROUNDS": "Дамику %d раз",
		"VICTORY_BANKER": "Выигрывает Банкир: %d vs %d",
		"VICTORY_PLAYER": "Выигрывает Игрок: %d vs %d",
		"VICTORY_TIE": "Игалите",
		"PAYOUT_TOGGLE_PLAYER": "Выплата игрок",
		"PAYOUT_TOGGLE_BANKER": "Выплата банкир",
		"PAYOUT_TOGGLE_TIE": "Выплата ничья",
		"BET_PROFILE": "Профиль ставок",
		"BET_PROFILE_SMALL": "Малые",
		"BET_PROFILE_MEDIUM": "Средние",
		"BET_PROFILE_LARGE": "Крупные",
		"BET_PROFILE_DESC_SMALL": "Небольшие ставки для тренировки",
		"BET_PROFILE_DESC_MEDIUM": "Реалистичная тренировка за столом",
		"BET_PROFILE_DESC_LARGE": "Сценарий крупного гостя",
		"ERR_UNPAID_BETS": "Ошибка. Сначала заверши обработку ставок!",
		"PAY_FIRST": "Сначала оплати!",
		"WAIT": "Ждите",
		"NOT_TIME": "Не время",
		"HEART_BET_IN_PROGRESS": "Сначала выберите сердце",
		"HEART_BET_SELECT_HEART": "Выберите сердце для ставки",
		"ALL_PAYOUTS_COMPLETED": "Все выплаты в учебном раунде завершены. Можно начинать новую раздачу.",
		"ALL_BETS_PAID": "Обработка ставок завершена. Следующая учебная раздача",
		"NO_WINNING_BETS": "В этом раунде нет выигрышных ставок. Следующая учебная раздача",
		"NO_ACTIVE_BETS": "Подготовьте ставки для учебного раунда",
		"ERR_WRONG_WINNER": "Ошибка! Неправильный выбор. Выиграл %s",
		"VICTORY_TOAST": "Выигрывает %s: %d vs %d",
		"PAYOUT_EMPTY_WARNING": "Ничего не забыл?",
		"ERR_HINT_NO_HEARTS": "Не хватает сердец",
		"ERR_HINT_NO_SCORE": "Не хватает очков",
		"HINT_USED_HEART": "-1 Сердце",
		"HINT_USED_SCORE": "-%d очков",
		
		# === ФАЗА СБОРА/ОПЛАТЫ СТАВОК ===
		"COLLECT_BUTTON": "Забрать",
		"PAY_BUTTON": "Оплатить",
		"ERR_COLLECT_WINNING": "Нельзя забрать выигрышную ставку!",
		"ERR_COLLECT_TIE_PUSH": "Нельзя забирать не проигранную ставку!",
		"ERR_PAY_BEFORE_COLLECT": "Сначала собери проигрышные ставки!",
		"ERR_CANNOT_COLLECT_TIE_PUSH": "Нельзя трогать при Tie! Не выиграла, не проиграла",
		"ERR_COMPLETE_BEFORE_COLLECT": "Сначала собери проигрышные ставки!",
		"ERR_COMPLETE_BEFORE_PAY": "Сначала оплати выигрышные ставки!",
		"ERR_WRONG_COLLECT_ORDER": "Неправильный порядок сбора ставок!",
		"ERR_WRONG_PAY_ORDER": "Неправильный порядок оплаты ставок!",
		"ERR_COLLECT_MAIN_FIRST": "Сначала собери все проигрышные ставки на основные",
		"ERR_COLLECT_TIE_FIRST": "Сначала собери все проигрышные ставки на игалите",
		"ERR_PAY_MAIN_FIRST": "Сначала оплати все выигрышные ставки на основные",
		"ERR_PAY_TIE_FIRST": "Сначала оплати все выигрышные ставки на игалите",

		# === НАСТРОЙКИ (SETTINGS SCENE) ===
		"SETTINGS_TITLE": "НАСТРОЙКИ",
		"SETTINGS_LIMITS": "ЛИМИТЫ",
		"SETTINGS_BETS_FILTER": "ФИЛЬТР СТАВОК И КАРТ",
		"SETTINGS_ADVANCED": "РАСШИРЕННЫЕ НАСТРОЙКИ",
		"SETTINGS_STORY": "СЮЖЕТ ГОСТЕЙ",
		"SETTINGS_STORY_BUTTON_ON": "Сюжет гостей включен",
		"SETTINGS_STORY_BUTTON_OFF": "Сюжет гостей выключен",
		"SETTINGS_STORY_DESCRIPTION": "Здесь настраивается, при каком количестве чаевых за стол приходит следующий гость.",
		"SETTINGS_STORY_TOGGLE_ON": "Сюжет ВКЛ",
		"SETTINGS_STORY_TOGGLE_OFF": "Сюжет ВЫКЛ",
		"SETTINGS_STORY_MODE_INFO_ON": "Новые гости приходят автоматически, когда чаевые достигают указанных порогов.",
		"SETTINGS_STORY_MODE_INFO_OFF": "Когда сюжет выключен, гостей можно включать и выключать вручную в разделе «Гости».",
		"SETTINGS_STORY_ROW_2": "Второй гость придет, когда чаевые достигнут:",
		"SETTINGS_STORY_ROW_3": "Третий гость придет, когда чаевые достигнут:",
		"SETTINGS_STORY_ROW_4": "Четвертый гость придет, когда чаевые достигнут:",
		"SETTINGS_STORY_ROW_5": "Пятый гость придет, когда чаевые достигнут:",
		"SETTINGS_STORY_ROW_6": "Шестой гость придет, когда чаевые достигнут:",
		"SETTINGS_STORY_RESET": "Сброс",
		"SETTINGS_STORY_RESET_TOOLTIP": "Сбросить порог",
		"SETTINGS_IMMORTALITY": "Свободная тренировка",
		"SETTINGS_IMMORTALITY_HINT": "Свободная тренировка (без потери сердец)",
		"SETTINGS_TEST_CARDS_ENABLED": "Задать карты вручную",
		"SETTINGS_CARD_SETTINGS": "Ручная раздача",
		"SETTINGS_CARD_SETTINGS_HINT": "Позволяет заранее задать первые карты раунда для отработки конкретных игровых ситуаций.",
		"SETTINGS_BANKER_1": "БАНКИР 1",
		"SETTINGS_BANKER_2": "БАНКИР 2",
		"SETTINGS_PLAYER_1": "ИГРОК 1",
		"SETTINGS_PLAYER_2": "ИГРОК 2",
		"SETTINGS_CARD_RANDOM": "Случайная",
		"SETTINGS_SECTION_SURVIVAL": "РЕЖИМ ВЫЖИВАНИЯ",
		"SETTINGS_SECTION_GAME_MODE": "РЕЖИМ ИГРЫ",
		"SETTINGS_SECTION_BETS": "СТАВКИ",
		"SETTINGS_SECTION_BET_SIZE": "РАЗМЕР СТАВОК",
		"SETTINGS_SECTION_TIP_PERCENTAGE": "ЧАЕВЫЕ",
		"SETTINGS_SECTION_LANGUAGE": "ЯЗЫК",
		"SETTINGS_SECTION_FREE_PRACTICE": "СВОБОДНАЯ ТРЕНИРОВКА",
		"SETTINGS_SECTION_CARD_BACK": "РУБАШКА",
		"SETTINGS_CARD_BACK_TIGER": "Тигр",
		"SETTINGS_CARD_BACK_LEOPARD": "Леопард",
		"SETTINGS_SECTION_SOUND": "ЗВУК",
		"SETTINGS_SURVIVAL_CHECKBOX": "Включить (7 жизней)",
		"SETTINGS_BET_PAIR_PLAYER": "Пара Игрока",
		"SETTINGS_BET_PAIR_BANKER": "Пара Банкира",
		"SETTINGS_BUTTON_APPLY": "ОК",
		"MODE_INFO_JUNKET": "Основные ставки: 2000-200000, шаг 500\nTie: 100-900, шаг 25\nПары: 100-900, шаг 25\nКомиссия банкира: 95%",
		"MODE_INFO_CLASSIC": "Основные ставки: 50-3000, шаг 1\nTie: 25-300, шаг 1\nПары: 25-200, шаг 1\nКомиссия банкира: 50%",
		"MODE_JUNKET_NAME": "Junket",
		"MODE_CLASSIC_NAME": "Classic",
		"LIMITS_CHANGE_PENDING": "Лимиты будут изменены на %s после завершения раздачи",
		"LIMITS_CHANGED": "Лимиты изменены на %s",
		
		# === РЕЖИМ ПОЗИЦИЙ ФИШЕК ===
		"SETTINGS_POSITION_MODE": "Позиции ставок",
		"POSITION_MODE_DEFAULT": "Обычный",
		"POSITION_MODE_RANDOM": "Случайные",
		"POSITION_MODE_MAX": "Максимум",
		"POSITION_MODE_REALISTIC": "Реалистичный",
		
		# === НАСТРОЙКИ ГОСТЕЙ ===
		"GUEST_SETTINGS_TITLE": "Настройки гостей",
		"GUEST_SETTINGS_BUTTON": "ГОСТИ",
		"GUEST_ENABLED": "Включён",
		"GUEST_CHARACTER": "Характер:",
		"GUEST_WEALTH": "Обеспеченность:",
		"GUEST_BALANCE": "Баланс:",
		"GUEST_CHARACTER_MODERATE": "Умеренный",
		"GUEST_CHARACTER_CAUTIOUS": "Осторожный",
		"GUEST_CHARACTER_GAMBLER": "Азартный",
		"GUEST_WEALTH_POOR": "Бедный",
		"GUEST_WEALTH_MEDIUM": "Средний",
		"GUEST_WEALTH_RICH": "Богатый",
		"GUEST_N": "Гость %d",
		"GUEST_LEFT_PATIENCE": "Гость %d ушел НЕДОВОЛЬНЫЙ",
		"GUEST_LEFT_BANKRUPTCY": "Гость %d ушел за фишками",
		"GUEST_RETURNED": "Гость %d вернулся",
		"GUEST_PROGRESSION_TITLE": "Прогрессия гостей",
		"GUEST_PROGRESSION_BUTTON": "ПРОГРЕССИЯ ГОСТЕЙ",
		"GUEST_PROGRESSION_AUTO_MODE": "Автоматический режим",
		"GUEST_COUNT_COLUMN": "Количество гостей",
		"TIPS_THRESHOLD_COLUMN": "Чаевые",
		"NEW_GUEST_ARRIVED": "Пришел новый гость",
		"CLOSE": "Закрыть",
		
		# ═══ HEART BET (Ставка сердцем) ═══
		"HEART_BET_CHANCE": "Шанс!",
		"HEART_BET_WON_PLAYER": "Поздравляем! Вы угадали! +2 ❤️",
		"HEART_BET_WON_BANKER": "Поздравляем! Вы угадали! +2 ❤️",
		"HEART_BET_WON_TIE": "Невероятно! Вы угадали Игалите! +7 ❤️",
		"HEART_BET_LOST": "Не повезло! Сердце потеряно 💔",
		"HEART_BET_TIE_DRAW": "Игалите! Попробуйте ещё раз 🔄",
		"HEART_BET_DECLINED": "Шанс упущен",
		
		# ═══ CHANCE CARDS (Карты шанса) ═══
		"USE_BUTTON": "Использовать",
		"CARD_CANNOT_USE": "Карту нельзя использовать сейчас",
		"CANNOT_USE_CHANCE": "Нельзя использовать шанс",
		"NO_CHANCES_AVAILABLE": "Нет доступных шансов",
		
		# === ГЛАВНОЕ МЕНЮ ===
		"MENU_TITLE": "БАККАРА ТРЕНАЖЁР",
		"MENU_ENTER_NAME": "Введите имя",
		"MENU_START": "Начать",
		"MENU_PLAY": "Играть",
		"MENU_LOGIN": "Войти",
		"MENU_REGISTER": "Регистрация",
		"MENU_GUEST": "Попробовать без регистрации",
		"MENU_USERNAME": "Логин",
		"MENU_PASSWORD": "Пароль",
		"MENU_LOADING": "Загрузка...",
		"MENU_LOADING_PERCENT": "Загрузка... %d%%",
		"MENU_READY": "Готово! Можно начинать",
		"MENU_ERROR_EMPTY": "Заполните все поля",
		"MENU_ERROR_USERNAME_SHORT": "Логин должен быть минимум 3 символа",
		"MENU_ERROR_PASSWORD_SHORT": "Пароль должен быть минимум 4 символа",
		"MENU_ERROR_LOGIN": "Неверный логин или пароль",
		"MENU_ERROR_REGISTER": "Пользователь уже существует",
		"MENU_ERROR_REGISTER_FAILED": "Ошибка регистрации",
		"MENU_TO_LOGIN": "Уже есть аккаунт? Войти",
		"MENU_TO_REGISTER": "Нет аккаунта? Регистрация"
	},
	"en": {
		"ERR_NATURAL_NO_DRAW": "Natural 8 or 9! No third card",
		"ERR_PLAYER_MUST_DRAW": "Error! Player with %d points must draw.",
		"ERR_PLAYER_NO_DRAW": "Error! Player with %d points must stand.",
		"ERR_BANKER_MUST_DRAW": "Error! Banker with %d points must draw.",
		"ERR_BANKER_NO_DRAW": "Error! Banker with %d points must stand.",
		"ERR_BANKER_MUST_DRAW_AFTER_PLAYER": "Error! Banker must draw after Player's %s.",
		"ERR_ALL_CARDS_OPENED": "Error! All cards are open. Choose winner.",
		"ERR_OPEN_FIRST_CARDS": "First deal 4 cards.",
		"ERR_FINISH_THIRD_CARDS": "Finish third card decisions first.",
		"ERR_OPEN_BANKER_CARD": "First open Banker's third card.",
		"ERR_FINISH_DEAL": "Complete the deal first.",
		"ERR_TIE_WRONG": "Error!",
		"INFO_NATURAL_CHOOSE_WINNER": "Natural 8 or 9! Choose winner",
		"INFO_BANKER_DEPENDS_ON_PLAYER": "Banker depends on Player's third card. Open it first.",
		"INFO_PLAYER_CARD_OPENED": "Player's card: %s. Now decide for Banker.",
		"INFO_BANKER_NO_DRAW_CHOOSE_WINNER": "Banker stands. Choose winner.",
		"INFO_ALL_OPENED_CHOOSE_WINNER": "All cards open. Choose winner.",
		"INFO_PLAYER_THIRD": "Player third: %s",
		"INFO_BANKER_THIRD": "Banker third: %s",
		"WIN_CORRECT": "Correct! Winner: %s — %s",
		"WIN_INCORRECT": "Wrong! You chose %s, but winner is %s — %s",
		"WIN_PLAYER": "Player",
		"WIN_BANKER": "Banker",
		"WIN_TIE": "Tie",
		"PLAYER": "Player",
		"BANKER": "Banker",
		"TIE_BUTTON": "Tie",
		"PAIR_PLAYER_TITLE": "Player Pair 11:1",
		"PAIR_BANKER_TITLE": "Banker Pair 11:1",
		"ACTION_BUTTON_CARDS": "Cards",
		"TOPBAR_HELP": "Reference",
		"TOPBAR_SETTINGS": "Settings",
		"TOPBAR_ROUNDS": "Deal: %d",
		"TOPBAR_TIPS": "Tips: %d",
		"HELP_TITLE": "Banker Third Card Table",
		"HELP_BANKER": "Banker",
		"HELP_PLAYER_THIRD": "Player's Third",
		"HELP_DRAW": "Draw",
		"HELP_NO_DRAW": "Stand",
		"BET_AMOUNT": "Bet: %d",
		"BANKER_BET": "Banker Bet: %d",
		"TIE_BET": "Tie Bet: %d",
		"COMMISSION_CORRECT": "Correct! Payout (commission): %d",
		"COMMISSION_INCORRECT": "Wrong! Correct payout: %d",
		"TIE_PAYOUT_CORRECT": "Correct! Tie payout (8:1): %d",
		"TIE_PAYOUT_INCORRECT": "Wrong! Correct Tie payout: %d",
		"ERR_INVALID_INPUT": "Invalid input! Enter an integer.",
		"BOTH_CARDS_NEEDED": "Both third cards needed.",
		"BANKER_NO_CARD_YET": "Banker doesn't need third card yet.",
		"BOTH_WRONG": "Error! Mark BOTH third cards.",
		"PAYOUT_BUTTON": "Payout",
		"PAYOUT_STAKE": "Stake: %s",
		"PAYOUT_AMOUNT_EMPTY": "Payout: —",
		"PAYOUT_AMOUNT": "Payout: %d",
		"DAMIKU": "No bets",
		"DAMIKU_NO_BETS": "Damiku! (deal without bets)",
		"DAMIKU_ROUNDS": "Damiku %d rounds",
		"VICTORY_BANKER": "Banker Wins: %d vs %d",
		"VICTORY_PLAYER": "Player Wins: %d vs %d",
		"VICTORY_TIE": "Tie",
		"PAYOUT_TOGGLE_PLAYER": "Player payout",
		"PAYOUT_TOGGLE_BANKER": "Banker payout",
		"PAYOUT_TOGGLE_TIE": "Tie payout",
		"BET_PROFILE": "Bet profile",
		"BET_PROFILE_SMALL": "Small",
		"BET_PROFILE_MEDIUM": "Medium",
		"BET_PROFILE_LARGE": "Large",
		"BET_PROFILE_DESC_SMALL": "Smaller bets for practice",
		"BET_PROFILE_DESC_MEDIUM": "Realistic table practice",
		"BET_PROFILE_DESC_LARGE": "VIP guest scenario",
		"ERR_UNPAID_BETS": "Error. Complete the bet handling first!",
		"PAY_FIRST": "Pay first!",
		"WAIT": "Wait",
		"NOT_TIME": "Not now",
		"HEART_BET_IN_PROGRESS": "Select a heart first",
		"HEART_BET_SELECT_HEART": "Select a heart to bet",
		"ALL_PAYOUTS_COMPLETED": "Training payouts completed. You can start the next deal.",
		"ALL_BETS_PAID": "Bet handling completed. Next training deal",
		"NO_WINNING_BETS": "No winning bets this round. Next training deal",
		"NO_ACTIVE_BETS": "Set up bets for the training round",
		"ERR_WRONG_WINNER": "Error! Wrong choice. Winner is %s",
		"VICTORY_TOAST": "%s Wins: %d vs %d",
		"PAYOUT_EMPTY_WARNING": "Didn't forget anything?",
		"ERR_HINT_NO_HEARTS": "Not enough hearts",
		"ERR_HINT_NO_SCORE": "Not enough score",
		"HINT_USED_HEART": "-1 Heart",
		"HINT_USED_SCORE": "-%d points",
		
		# === BET COLLECTION/PAYMENT PHASE ===
		"COLLECT_BUTTON": "Collect",
		"PAY_BUTTON": "Pay",
		"ERR_COLLECT_WINNING": "Cannot collect winning bet!",
		"ERR_COLLECT_TIE_PUSH": "Cannot collect non-losing bet!",
		"ERR_PAY_BEFORE_COLLECT": "Collect losing bets first!",
		"ERR_CANNOT_COLLECT_TIE_PUSH": "Cannot touch on Tie! Not won, not lost",
		"ERR_COMPLETE_BEFORE_COLLECT": "Collect losing bets first!",
		"ERR_COMPLETE_BEFORE_PAY": "Pay winning bets first!",
		"ERR_WRONG_COLLECT_ORDER": "Wrong collection order!",
		"ERR_WRONG_PAY_ORDER": "Wrong payment order!",
		"ERR_COLLECT_MAIN_FIRST": "Collect all losing main bets first",
		"ERR_COLLECT_TIE_FIRST": "Collect all losing tie bets first",
		"ERR_PAY_MAIN_FIRST": "Pay all winning main bets first",
		"ERR_PAY_TIE_FIRST": "Pay all winning tie bets first",

		# === SETTINGS (SETTINGS SCENE) ===
		"SETTINGS_TITLE": "SETTINGS",
		"SETTINGS_LIMITS": "LIMITS",
		"SETTINGS_BETS_FILTER": "BETS FILTER AND CARDS",
		"SETTINGS_ADVANCED": "ADVANCED SETTINGS",
		"SETTINGS_STORY": "GUEST STORY",
		"SETTINGS_STORY_BUTTON_ON": "Guest story on",
		"SETTINGS_STORY_BUTTON_OFF": "Guest story off",
		"SETTINGS_STORY_DESCRIPTION": "Set how many tips are needed before the next guest joins the table.",
		"SETTINGS_STORY_TOGGLE_ON": "Story ON",
		"SETTINGS_STORY_TOGGLE_OFF": "Story OFF",
		"SETTINGS_STORY_MODE_INFO_ON": "New guests join automatically when tips reach the thresholds below.",
		"SETTINGS_STORY_MODE_INFO_OFF": "When story mode is off, you can enable or disable guests manually in the Guests section.",
		"SETTINGS_STORY_ROW_2": "Second guest joins when tips reach:",
		"SETTINGS_STORY_ROW_3": "Third guest joins when tips reach:",
		"SETTINGS_STORY_ROW_4": "Fourth guest joins when tips reach:",
		"SETTINGS_STORY_ROW_5": "Fifth guest joins when tips reach:",
		"SETTINGS_STORY_ROW_6": "Sixth guest joins when tips reach:",
		"SETTINGS_STORY_RESET": "Reset",
		"SETTINGS_STORY_RESET_TOOLTIP": "Reset threshold",
		"SETTINGS_IMMORTALITY": "Free Practice",
		"SETTINGS_IMMORTALITY_HINT": "Free Practice (no heart loss)",
		"SETTINGS_TEST_CARDS_ENABLED": "Set cards manually",
		"SETTINGS_CARD_SETTINGS": "Manual Deal",
		"SETTINGS_CARD_SETTINGS_HINT": "Lets you preselect the opening cards to practice specific round scenarios.",
		"SETTINGS_BANKER_1": "BANKER 1",
		"SETTINGS_BANKER_2": "BANKER 2",
		"SETTINGS_PLAYER_1": "PLAYER 1",
		"SETTINGS_PLAYER_2": "PLAYER 2",
		"SETTINGS_CARD_RANDOM": "Random",
		"SETTINGS_SECTION_SURVIVAL": "SURVIVAL MODE",
		"SETTINGS_SECTION_GAME_MODE": "GAME MODE",
		"SETTINGS_SECTION_BETS": "BETS",
		"SETTINGS_SECTION_BET_SIZE": "BET SIZE",
		"SETTINGS_SECTION_TIP_PERCENTAGE": "TIPS",
		"SETTINGS_SECTION_LANGUAGE": "LANGUAGE",
		"SETTINGS_SECTION_FREE_PRACTICE": "FREE PRACTICE",
		"SETTINGS_SECTION_CARD_BACK": "CARD BACK",
		"SETTINGS_CARD_BACK_TIGER": "Tiger",
		"SETTINGS_CARD_BACK_LEOPARD": "Leopard",
		"SETTINGS_SECTION_SOUND": "SOUND",
		"SETTINGS_SURVIVAL_CHECKBOX": "Enable (7 lives)",
		"SETTINGS_BET_PAIR_PLAYER": "Player Pair",
		"SETTINGS_BET_PAIR_BANKER": "Banker Pair",
		"SETTINGS_BUTTON_APPLY": "OK",
		"MODE_INFO_JUNKET": "Main bets: 2000-200000, step 500\nTie: 100-900, step 25\nPairs: 100-900, step 25\nBanker commission: 95%",
		"MODE_INFO_CLASSIC": "Main bets: 50-3000, step 1\nTie: 25-300, step 1\nPairs: 25-200, step 1\nBanker commission: 50%",
		"MODE_JUNKET_NAME": "Junket",
		"MODE_CLASSIC_NAME": "Classic",
		"LIMITS_CHANGE_PENDING": "Limits will be changed to %s after the deal is completed",
		"LIMITS_CHANGED": "Limits changed to %s",
		
		# === CHIP POSITION MODE ===
		"SETTINGS_POSITION_MODE": "Bet positions",
		"POSITION_MODE_DEFAULT": "Default",
		"POSITION_MODE_RANDOM": "Random",
		"POSITION_MODE_MAX": "Maximum",
		"POSITION_MODE_REALISTIC": "Realistic",
		
		# === GUEST SETTINGS ===
		"GUEST_SETTINGS_TITLE": "Guest Settings",
		"GUEST_SETTINGS_BUTTON": "GUESTS",
		"GUEST_ENABLED": "Enabled",
		"GUEST_CHARACTER": "Character:",
		"GUEST_WEALTH": "Wealth:",
		"GUEST_BALANCE": "Balance:",
		"GUEST_CHARACTER_MODERATE": "Moderate",
		"GUEST_CHARACTER_CAUTIOUS": "Cautious",
		"GUEST_CHARACTER_GAMBLER": "Gambler",
		"GUEST_WEALTH_POOR": "Poor",
		"GUEST_WEALTH_MEDIUM": "Medium",
		"GUEST_WEALTH_RICH": "Rich",
		"GUEST_N": "Guest %d",
		"GUEST_LEFT_PATIENCE": "Guest %d left UNHAPPY",
		"GUEST_LEFT_BANKRUPTCY": "Guest %d left for chips",
		"GUEST_RETURNED": "Guest %d returned",
		"GUEST_PROGRESSION_TITLE": "Guest Progression",
		"GUEST_PROGRESSION_BUTTON": "GUEST PROGRESSION",
		"GUEST_PROGRESSION_AUTO_MODE": "Auto Mode",
		"NEW_GUEST_ARRIVED": "A new guest has arrived",
		"CLOSE": "Close",
		
		# === HEART BET ===
		"HEART_BET_CHANCE": "Chance!",
		"HEART_BET_WON_PLAYER": "Congratulations! You guessed! +2 ❤️",
		"HEART_BET_WON_BANKER": "Congratulations! You guessed! +2 ❤️",
		"HEART_BET_WON_TIE": "Incredible! You guessed Tie! +7 ❤️",
		"HEART_BET_LOST": "Unlucky! Heart lost 💔",
		"HEART_BET_TIE_DRAW": "Tie! Try again 🔄",
		"HEART_BET_DECLINED": "Chance missed",
		
		# === CHANCE CARDS ===
		"USE_BUTTON": "Use",
		"CARD_CANNOT_USE": "Card cannot be used now",
		"CANNOT_USE_CHANCE": "Cannot use chance",
		"NO_CHANCES_AVAILABLE": "No chances available",
		
		# === MAIN MENU ===
		"MENU_TITLE": "BACCARAT TRAINER",
		"MENU_ENTER_NAME": "Enter your name",
		"MENU_START": "Start",
		"MENU_PLAY": "Play",
		"MENU_LOGIN": "Login",
		"MENU_REGISTER": "Register",
		"MENU_GUEST": "Try without registration",
		"MENU_USERNAME": "Username",
		"MENU_PASSWORD": "Password",
		"MENU_LOADING": "Loading...",
		"MENU_LOADING_PERCENT": "Loading... %d%%",
		"MENU_READY": "Ready! You can start",
		"MENU_ERROR_EMPTY": "Fill in all fields",
		"MENU_ERROR_USERNAME_SHORT": "Username must be at least 3 characters",
		"MENU_ERROR_PASSWORD_SHORT": "Password must be at least 4 characters",
		"MENU_ERROR_LOGIN": "Invalid username or password",
		"MENU_ERROR_REGISTER": "User already exists",
		"MENU_ERROR_REGISTER_FAILED": "Registration error",
		"MENU_TO_LOGIN": "Already have an account? Login",
		"MENU_TO_REGISTER": "No account? Register"
	}
}

static var _current_lang: String = "ru"

static func t(key: String, args = []) -> String:
	var text = DATA[_current_lang].get(key, key)
	if args.size() > 0:
		text = text % args
	return text

static func set_lang(lang: String):
	if lang in DATA:
		_current_lang = lang
		
static func get_lang() -> String:
	return _current_lang
